### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by chris-sanders** [la-cc/anything-llm-helm-chart#1]
First, thanks for putting together a helm chart, that's what's held me back from spending some time looking at AnythingLLM.

I just wanted to find out from an initial pass what you're intentions are. I see this is new, so I completely understand if the to-do list is long.

First, I noticed that you're using a container from your repository and not from AnythingLLMs repository. It looks like AnythingLLM doesn't provide a lot of tags. Are you rebuilding the image to have more granular tags, or something else?

On the image, the tag doesn't match the AnythingLLM version, are you tagging based on the helm chart, is there any way for someone to know what AnythingLLM version is being deployed? I would assume the upstream would want people to know/say that if they had an issue.

Currently it looks like all API keys are provided in plain text via the values file. Did I miss something, or do you intend to add support for using secrets?

Do you have a relationship with the upstream? Is this considered an 'official' helm chart or has that conversation not happened yet?

**Comment by la-cc** [comment]
Hi @chris-sanders, 

gladly, that was also our challenge with @deB4SH. We then deployed Anything-LLM, saw what potential it had and built a helm chart from it.

_I just wanted to find out from an initial pass what you're intentions are. I see this is new, so I completely understand if the to-do list is long._ 

-> We make Anything-LLM available via an Ingress and didn't want anyone to have access to the Anything-LLM before users are created. 

_First, I noticed that you're using a container from your repository and not from AnythingLLMs repository. It looks like AnythingLLM doesn't provide a lot of tags. Are you rebuilding the image to have more granular tags, or something else?_

-> This is because, as you have already seen, there are no fixed tags other than master. This had caused images to be pulled with an unknown change when moving the pods and this caused us to crash because, for example, we had forgotten to change the directory to a non-root user during a change. We rebuild it and set fix tags, so we know which version are used. It will be nice if anything-llm provide an app version so we can pin the tag to the app version. 

_On the image, the tag doesn't match the AnythingLLM version, are you tagging based on the helm chart, is there any way for someone to know what AnythingLLM version is being deployed? I would assume the upstream would want people to know/say that if they had an issue._ 

-> Currently, the tag does not provide any information about which app version is being used. We would like to map it to an app version. We will get in touch with Anything-LLM contributors and see if they will set up tags. Our goal is not to maintain the fork.

_Currently it looks like all API keys are provided in plain text via the values file. Did I miss something, or do you intend to add support for using secrets?_

 -> Yes, but that's just for quick testing. There is already the option to reference a secret (secret.name). It will then looks like:

```
# -- Secret configuration.
secret:
  # -- Enable secrets.
  enabled: true
  # -- Name of the secret, if not set, a secret is generated.
  name: "your-secret"
 ```
 
 _Do you have a relationship with the upstream? Is this considered an 'official' helm chart or has that conversation not happened yet?_  Not yet, but hopefully soon.

**Comment by chris-sanders** [comment]
Great thanks for the answers and for putting together a chart so I can check it out without having to write one :)
